server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://34.50.93.104:5431/restaurant
    username: mengseu
    password: 123
    driver-class-name: org.postgresql.Driver