server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver