business:
  info:
    name: "Business Development Mode"
    description: "Business API"
    version: "1.0.0"

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.101.39.118:5431/business
    username: mengseu
    password: 123
