business:
  info:
    name: "Business Development Mode"
    description: "Business API"
    version: "1.0.0"

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.50.93.104:5431/busines
    username: mengseu
    password: 123

