server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://34.101.39.118:5430/oauth2
    username: mengseu
    password: 123
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: it.chhaya@gmail.com
    password: duuf wtgf nobv hggc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true